### ISSUE TITLE
[Feature] There are things on PlutoGridSettings that aren't customizable

### ISSUE THREAD

**Issue by Macacoazul01** [doonfrs/pluto_grid_plus#13]
the abstract class `PlutoGridSettings` defines a big part of the grid visuals and not every parameter defined there is customizable on the creation of the table with `PlutoGridStyleConfig`.

Using as a sample, we could't find a way to change `gridPadding` parameter and it breaks the visual in our code (made a fork of the original repo and forced it to be 0 to use there, but this isn't the correct way of solving it on the package).

There should be a way to everything there be the default config but not the only one.

**Comment by RADeveloping** [comment]
This is one approach:

https://github.com/bosskmk/pluto_grid/commit/123276946313098c20d2e656cb7b0169b2753a41

**Comment by Macacoazul01** [comment]
Was this merged here?

**Comment by Macacoazul01** [comment]
Added the commit. Gonna merge
