### ISSUE TITLE
[Help] how to avoid row value "null" display when data is null

### ISSUE THREAD

**Issue by yunchiri** [doonfrs/pluto_grid_plus#19]
PlutoColumn(title: "id", field: "id", type: PlutoColumnType.text()),

when data value is **['1', null, '3']**

<img width="170" alt="image" src="https://github.com/doonfrs/pluto_grid_plus/assets/1159660/022b6412-21d0-4bf8-a968-c0153f766c3e">

how to replace "null" to empty

I have solution like
```
  List<PlutoColumn> columns = [
    PlutoColumn(
        title: "id",
        field: "id",
        type: PlutoColumnType.text(),
        formatter: (value) {
          if (value == null) return '';
          return value.toString();
        },
        readOnly: true),
  ];
```
but is there are simply way?

**Comment by design2023** [comment]
You have to use the renderer property and return the Text widget with the value by checking the value before if it was null to view anything else.

**Comment by doonfrs** [comment]
renderer should give you full control of the cell widget, or you may change null to '' when you build the cells array ( alter the data )
