### ISSUE TITLE
[Bug] F5 Key ist not working in browser

### ISSUE THREAD

**Issue by mirror89** [doonfrs/pluto_grid_plus#22]
### Steps to reproduce the bug
1. Select a cell in your grid while using Google Chrome (for example)
2. Try to use F5 to reload browser window

-> Using the reload icon in browser works fine. F5 not!

### Expected results
If F5 is pressed, the browser has to reload! Not only if nothing is selected or if there is no focus on grid

### Actual results
If focus is on grid, F5 is not working

### Code sample
Use any grid! For example: https://weblaze.dev/pluto_grid/build/web/#feature/column-footer

### Execution Environment
Flutter version is 3.19.0

**PlutoGrid version**
8.3.0

**OS**
Google Chrome, Firefox, Windows 10, Windows 11, Ubuntu 22.04.4 LTS

**Comment by doonfrs** [comment]
Unfortunately, this is a flutter web issue, it is not related to the current project.
check this example: 
https://flutter.github.io/samples/web/simplistic_editor/

**Comment by mirror89** [comment]
No, it is not! It is a pluto_grid error! In our complete application, this error only occurs in the pluto_grid without exception!

**Comment by doonfrs** [comment]
Are you able to refresh the page here:
https://flutter.github.io/samples/web/simplistic_editor/

**Comment by mirror89** [comment]
Sure! It refreshes! It refreshes too, when klicked somewhere^^

**Comment by mirror89** [comment]
Hey! REOPEN the issue please! It is a pluto grid issue! Checked that.
