### ISSUE TITLE
Update Package to Support intl: ^0.19.0

### ISSUE THREAD

**Issue by JeffOlajos** [doonfrs/pluto_grid_plus#23]
Please update package to support intl: ^0.19.0

**Comment by doonfrs** [comment]
Hi @JeffOlajos 
I don't think it is safe to upgrade as flutter stable version still depends on 0.18
flutter_localization and some other packages will break the build
https://github.com/flutter/flutter/issues/139861

**Comment by JeffOlajos** [comment]
Seems a number of other packages we use are now dependeant on Intl: 0.19.0 so IM not sure what the issue might be
