### ISSUE TITLE
[Bug] set data into a hidden column

### ISSUE THREAD

**Issue by darkomenx** [doonfrs/pluto_grid_plus#24]
Hello doonfrs,

**I would like to implement features :** hidden/display dynamically children row of another specific row.

I base my implementation of this example of official repo : [add remove row column](https://github.com/bosskmk/pluto_grid/blob/master/demo/lib/screen/feature/add_and_remove_column_row_screen.dart)

**In particular of this function :** `handleAddRows()` which works with `e.cells['status']!.value` for settings value of the new rows.

**BUT (issue) :** My grid has a hidden defined Column that is not present on `e.cells` collection (provided by (`_stateManager!.getNewRows()`). This is a issue because when those rows are injected into the grid the hidden column is mandatory and it generate error on each row because I hadn't filled the cells.

**QUESTION :** How can I set data of the hidden column dynamically ? Is there another trick for doing this ? Is this a real issue ?

**Technical context :** 
OS : windows 11
Dart : 3.3.0
Flutter : 3.19.1 (channel stable)
pluto_grid_plus : 8.3.0

Thank you for your support.

**Comment by doonfrs** [comment]
Hi @darkomenx 
Maybe you can add an empty value in cells maps, I don't know if it is good for the grid to ignore not found cell field, the exception is a sign of something missing in the data and this is the default behavior, so you can do this workaround by filling an empty value, it should work.
