### ISSUE TITLE
[Bug] Sample is breaking because 8.3.1 isnt avaliable

### ISSUE THREAD

**Issue by Macacoazul01** [doonfrs/pluto_grid_plus#27]
If you try to run pub get on the whole project it will throw an error saying that version 8.3.1 isnt avaliable on pub.dev

`demo/pubspec.yaml`:

![image](https://github.com/doonfrs/pluto_grid_plus/assets/57464965/ec23e1ce-fc5a-46bc-9fa7-dbc5a407d2e1)

`packages/pluto_grid_plus_export/example/pubspec.yaml`:

![image](https://github.com/doonfrs/pluto_grid_plus/assets/57464965/4b5c74cd-20fc-4831-b582-e1633e8f90f9)

**Comment by Macacoazul01** [comment]
@doonfrs when are you planning to release the new version?

**Comment by doonfrs** [comment]
8.4 released
https://pub.dev/packages/pluto_grid_plus
