### ISSUE TITLE
[Help] How to create a custom filter for Dates using a datePicker?

### ISSUE THREAD

**Issue by fdOli** [doonfrs/pluto_grid_plus#31]
Hello,
Is possible to have a custom input widget for the filter(s) instead the input text? I need one to filter dates, more specifically 'between' dates. My idea is to have two date picker(s), one for the START and one for END date in the filter area.
Please let me know how I should implement this.

*I posted this question on the original pluto_grid but I believe it's not being maintained anymore.

Thanks!

**Comment by doonfrs** [comment]
I need this in my current project so the feature should be available soon, I can not guarantee time but roughly within 10 days.

best;

**Comment by doonfrs** [comment]
You can start by using the filterWidget attribute for PlutoColumn when you build the grid columns array, this will allow you to make your custom widget ( data picker maybe) and control the events after that, you need to manually filter the data and refresh the grid for sure.

**Comment by fdOli** [comment]
Thank you so much!
