### ISSUE TITLE
[Help] Is there a way to put Widgets (mainly IconButtons and Icons) inside cells

### ISSUE THREAD

**Issue by MuKhAlm** [doonfrs/pluto_grid_plus#64]
### Description

I'm using the table to display students in rows. Each student is supposed to have actions related to it (edit, suspend, remove, etc.)

Those actions are supposed to be accessed via IconButtons inside a cell (In a column titled Actions)

Is there a way to get that functionality?

**Comment by doonfrs** [comment]
Hi, @MuKhAlm 
The row as renderer property, it should help you to add any widget dynamically instead of only text

**Comment by MuKhAlm** [comment]
> Hi, @MuKhAlm 
> 
> The row as renderer property, it should help you to add any widget dynamically instead of only text

Thank you very much!

(It feels like I'm doing something I should be doing but hey it gets the job done!)
