### ISSUE TITLE
[Other] Pull requests from old repo?

### ISSUE THREAD

**Issue by bastaware** [doonfrs/pluto_grid_plus#7]
Will the pull requests from the old repo be merged in? Or do they have to be created again?

I have this pretty simple PR laying dormant:
https://github.com/bosskmk/pluto_grid/pull/852/commits/a0c0601375d9880d4b2dd08e84e167c14e758b1d

**Comment by doonfrs** [comment]
Hi @bastaware could you please explain why did you use utc? I am afraid this solution may not work for all timezones.

**Comment by bastaware** [comment]
The problem appears in the months of change summer/wintertime. The days count will be wrong because of the missing/extra hour.

utc works because there is no summer/winter time. I'm sure there are other solutions to this, it just seemed as an easy fix.

It can easily be testet:

https://github.com/bosskmk/pluto_grid/issues/826

**Comment by doonfrs** [comment]
Thank you, could you please create the PR on the current package, I will review & merge it.

**Comment by Macacoazul01** [comment]
@doonfrs im gonna send a message in each pr from the 20 in the original package. 

which you already merged?
