### ISSUE TITLE
[Bug] When pluto grid mode is selectWithOneTap, refreshing does not work even if you press F5 or F12.

### ISSUE THREAD

**Issue by 96kyle** [doonfrs/pluto_grid_plus#74]
When pluto grid mode is selectWithOneTap, pressing F5 does not refresh and pressing F12 does not open developer tools.

**Flutter version**
Flutter version is 3.19.5

**PlutoGrid version**
PlutoGrid version is 8.4.2

**OS**
Windows 11

**Comment by satvikreddy** [comment]
I am facing the same issue. Is there a workaround?
