### ISSUE TITLE
[Help] LateInitializationError

### ISSUE THREAD

**Issue by VittorioParagallo** [doonfrs/pluto_grid_plus#76]
Only during development, in case of doing a hot-reload, the stateManager becomes invalid:
LateError (LateInitializationError: Field 'plutoGridStateManager' has not been initialized.)
How did you manage to solve it?

**Comment by doonfrs** [comment]
I don't have the issues with hot reload, my code:
at class level:
`  PlutoGridStateManager? _stateManager;
`
then in the widget creation:
```
onLoaded: (PlutoGridOnLoadedEvent event) {
          _stateManager = event.stateManager;
```
also I put the grid widget inside statefullbuidler to separate the grid state from the main widget state.
